import Head from "next/head";
import { db } from "@/firebase/config";
import { motion } from "framer-motion";
import { doc, getDoc, setDoc, increment, FieldValue } from "firebase/firestore";

const Home = () => {
	const incrementClicks = async () => {
		try {
			const docRef = doc(db, "test", "clicks");
			const temp = 1;

			await setDoc(docRef, {
				// curr: FieldValue.increment(),
				curr: (await getDoc(docRef)).data().curr + 1,
			});
		} catch (err) {
			console.log(err);
		}
	};

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="w-full min-h-screen bg-gray-200 flex flex-col items-center place-content-center">
				<motion.button
					onClick={() => {
						incrementClicks();
					}}
					whileTap={{ scale: 0.6 }}
					className="text-lg py-1 px-6 bg-blue-500 text-white rounded-xl shadow-sm shadow-gray-400 hover:bg-blue-600
        transition duration-300 font-semibold outline-none focus:outline-none"
				>
					Click Me
				</motion.button>
			</main>
		</>
	);
};

export default Home;
